version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.2
    - 2.18.3
    - 2.18.4
    - 2.18.5
    - 2.18.6
  - dependency-name: kreait/firebase-bundle
    versions:
    - 2.4.0
  - dependency-name: symfony/console
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: symfony/maker-bundle
    versions:
    - 1.28.0
    - 1.29.0
    - 1.29.1
    - 1.30.0
    - 1.30.1
    - 1.30.2
  - dependency-name: sensio/framework-extra-bundle
    versions:
    - 6.0.0
    - 6.1.0
    - 6.1.1
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/flex
    versions:
    - 1.12.1
    - 1.12.2
